In [40]:
from mysql import connector
myconnection =connector.connect(
    host="localhost",
    user="root",
    password="123456789",
    database ="Redbus"
)
cursor = myconnection.cursor()
cursor

In [42]:
import pandas as pd
(r"C:/Users/DELL/OneDrivedf = pd.read_csv/문서/guvi_projects/bus_routes.csv")

'C:/Users/DELL/OneDrivedf = pd.read_csv/문서/guvi_projects/bus_routes.csv'

In [43]:
import pandas as pd
df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Esplanade - 176|04:00,Non AC Seater (2+3),04:00,05h 50m,09:50,4.3,INR 165,49 Seats available
1,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) BARASAT-DIGHA via Bally - 38|05:40,Non AC Seater (2+3),05:40,04h 30m,10:10,3.5,INR 161,43 Seats available
2,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,"WBTC (CTC) BARASAT-DIGHA via Esplanade, Karuna...",Non AC Seater (2+3),09:55,05h 00m,14:55,3.5,INR 165,43 Seats available
3,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Bally - 26|10:00,Non AC Seater (2+3),10:00,04h 45m,14:45,3.3,INR 161,40 Seats available
4,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Bally - 26|10:40,Non AC Seater (2+3),10:40,04h 45m,15:25,3.1,INR 161,44 Seats available
...,...,...,...,...,...,...,...,...,...,...
420,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Droupadi City Service,A/C Seater (2+3),15:20,02h 50m,18:10,3.0,180,60 Seats available
421,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Swapna Paribahan,Non AC Seater (2+3),16:55,04h 30m,21:25,3.0,INR 150,25 Seats available
422,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Droupadi Paribahan,A/C Seater (2+3),14:10,02h 48m,16:58,2.7,INR 160,61 Seats available
423,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,KRISHNAKALI,A/C Seater (2+3),14:45,02h 45m,17:30,2.2,INR 165,61 Seats available
424,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Droupadi Bus Service,Non AC Seater (2+3),16:20,02h 50m,19:10,2.2,INR 121,54 Seats available

In [44]:
df = pd.read_csv(r"C:\Users\DELL\OneDrive\문서\guvi_projects\ap_bus_details.csv")
df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Chittoor (Andhra Pradesh) to Bangalore,https://www.redbus.in/bus-tickets/chittoor-and...,APSRTC - 5118,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",01:30,02h 50m,04:20,3.1,INR 277,25 Seats available
1,Chittoor (Andhra Pradesh) to Bangalore,https://www.redbus.in/bus-tickets/chittoor-and...,APSRTC - 9035,Express(Non AC Seater),04:00,03h 00m,07:00,4.2,INR 186,45 Seats available
2,Chittoor (Andhra Pradesh) to Bangalore,https://www.redbus.in/bus-tickets/chittoor-and...,APSRTC - 9057,Express(Non AC Seater),04:30,03h 15m,07:45,4.1,INR 186,42 Seats available
3,Chittoor (Andhra Pradesh) to Bangalore,https://www.redbus.in/bus-tickets/chittoor-and...,APSRTC - 9129,Express(Non AC Seater),05:00,03h 25m,08:25,3.7,INR 186,45 Seats available
4,Chittoor (Andhra Pradesh) to Bangalore,https://www.redbus.in/bus-tickets/chittoor-and...,APSRTC - 9037,Express(Non AC Seater),05:30,03h 25m,08:55,4.0,INR 186,43 Seats available
...,...,...,...,...,...,...,...,...,...,...
1549,Hyderabad to Markapuram,https://www.redbus.in/bus-tickets/hyderabad-to...,New Slnst Travels,A/C Sleeper (2+1),22:00,06h 45m,04:45,3.9,3799,2 Seats available
1550,Hyderabad to Markapuram,https://www.redbus.in/bus-tickets/hyderabad-to...,SMKAT Travels,Volvo Multi-Axle B9R A/c Semi Sleeper (2+2),20:50,08h 10m,05:00,1.5,INR 3999,49 Seats available
1551,Hyderabad to Markapuram,https://www.redbus.in/bus-tickets/hyderabad-to...,Harikrishna Travels,Non A/C Seater / Sleeper (2+1),23:00,06h 00m,05:00,3.6,INR 750,31 Seats available
1552,Hyderabad to Markapuram,https://www.redbus.in/bus-tickets/hyderabad-to...,IVR Tours and Travels,Non A/C Seater / Sleeper (2+1),21:30,07h 40m,05:10,1.5,INR 549,35 Seats available
1553,Hyderabad to Markapuram,https://www.redbus.in/bus-tickets/hyderabad-to...,Harikrishna Travels,Non A/C Seater / Sleeper (2+1),22:00,07h 00m,05:00,0.0,INR 700,40 Seats available

In [45]:
df = pd.read_csv(r"C:\Users\DELL\OneDrive\문서\guvi_projects\assam_bus_details.csv")
df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,PEPSU (Punjab) - 67085,Volvo AC Seater (2+2),02:00,06h 00m,08:00,4.0,INR 826,27 Seats available
1,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,PEPSU (Punjab) - 67085,Volvo AC Seater (2+2),03:00,05h 00m,08:00,4.7,INR 711,26 Seats available
2,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,PEPSU (Punjab) - 67069,Volvo AC Seater (2+2),06:40,06h 50m,13:30,4.9,INR 826,30 Seats available
3,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,PEPSU (Punjab) - 67069,Volvo AC Seater (2+2),08:00,05h 30m,13:30,4.2,INR 711,26 Seats available
4,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,PEPSU (Punjab) - 67160,Volvo AC Seater (2+2),11:45,05h 30m,17:15,4.6,INR 711,29 Seats available
...,...,...,...,...,...,...,...,...,...,...
889,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66655,HVAC Seater (2+3),04:40,05h 00m,09:40,3.7,INR 469,54 Seats available
890,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,PEPSU (Punjab) - 66656,HVAC Seater (2+3),11:45,05h 00m,16:45,3.7,INR 469,53 Seats available
891,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,DHILLON BUS,NON A/C Seater (2+3),09:15,06h 15m,15:30,5.0,INR 465,51 Seats available
892,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,Patiala Bus Highways Service (P) Ltd,Non AC Seater (2+3),15:00,05h 15m,20:15,3.6,INR 465,50 Seats available
893,Patiala to Amritsar,https://www.redbus.in/bus-tickets/patiala-to-a...,GK Travels,Bharat Benz A/C Seater /Sleeper (2+1),04:55,04h 05m,09:00,1.6,759,16 Seats available

In [46]:
df = pd.read_csv(r"C:\Users\DELL\OneDrive\문서\guvi_projects\chandigarh_bus_details.csv")
df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...,HRTC - 551,A/C Executive (2+3),15:30,05h 55m,21:25,3.9,INR 400,38 Seats available
1,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...,HRTC - 525,Ordinary 3+2 Non AC Seater,16:50,05h 50m,22:40,3.9,INR 290,26 Seats available
2,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...,HRTC - 526,Ordinary 3+2 Non AC Seater,17:00,06h 00m,23:00,3.9,INR 275,33 Seats available
3,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...,HRTC - 587,Ordinary 3+2 Non AC Seater,18:25,04h 35m,23:00,3.9,INR 285,33 Seats available
4,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...,HRTC - 541,Ordinary 3+2 Non AC Seater,19:14,05h 16m,00:30,3.9,INR 290,35 Seats available
...,...,...,...,...,...,...,...,...,...,...
481,Chandigarh to Haridwar,https://www.redbus.in/bus-tickets/chandigarh-t...,SHRI KRISHNA TRAVELS (JAI SHREE GANESH YATRA CO.),A/C Sleeper (2+2),23:45,06h 00m,05:45,3.7,INR 1199,40 Seats available
482,Chandigarh to Haridwar,https://www.redbus.in/bus-tickets/chandigarh-t...,Laxmi holidays,VE A/C Semi Sleeper (2+2),23:55,06h 35m,06:30,4.7,INR 899,25 Seats available
483,Chandigarh to Haridwar,https://www.redbus.in/bus-tickets/chandigarh-t...,SHRI KRISHNA TRAVELS (JAI SHREE GANESH YATRA CO.),VE A/C Seater / Sleeper (2+1),23:55,05h 40m,05:35,4.1,INR 899,23 Seats available
484,Chandigarh to Haridwar,https://www.redbus.in/bus-tickets/chandigarh-t...,City Land Travels,Volvo A/C Semi Sleeper (2+2),23:55,05h 06m,05:01,3.8,405,19 Seats available
485,Chandigarh to Haridwar,https://www.redbus.in/bus-tickets/chandigarh-t...,SHRI KRISHNA TRAVELS (JAI SHREE GANESH YATRA CO.),A/C Sleeper (2+2),23:59,05h 46m,05:45,3.7,INR 1199,40 Seats available

In [47]:

df =pd.read_csv(r"C:\Users\DELL\OneDrive\문서\guvi_projects\Haryana_bus_details.csv")
df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 2100720,Ordinary 3+2 Non AC Seater,05:00,09h 50m,14:50,4.1,INR 512,31 Seats available
1,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 6,Himsuta AC Seater Volvo/Scania 2+2,06:45,09h 25m,16:10,4.6,INR 912,27 Seats available
2,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 592,A/C Executive (2+3),08:05,10h 05m,18:10,3.7,INR 632,40 Seats available
3,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 129,Ordinary 3+2 Non AC Seater,08:50,09h 50m,18:40,3.8,INR 512,37 Seats available
4,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 7,Himsuta AC Seater Volvo/Scania 2+2,09:25,09h 05m,18:30,4.3,INR 912,22 Seats available
...,...,...,...,...,...,...,...,...,...,...
933,Baddi (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/baddi-himach...,HRTC - 6708,Ordinary 3+2 Non AC Seater,05:30,07h 40m,13:10,3.7,INR 318,37 Seats available
934,Baddi (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/baddi-himach...,HRTC - 6753,Ordinary 3+2 Non AC Seater,10:20,07h 10m,17:30,3.2,INR 325,32 Seats available
935,Baddi (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/baddi-himach...,HRTC - 6649,Ordinary 3+2 Non AC Seater,13:15,07h 15m,20:30,3.3,INR 325,42 Seats available
936,Baddi (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/baddi-himach...,HRTC - 6709,Ordinary 3+2 Non AC Seater,19:30,07h 10m,02:40,3.8,INR 325,34 Seats available
937,Baddi (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/baddi-himach...,HRTC - 6639,A/C Executive (2+3),20:45,06h 45m,03:30,3.8,INR 430,42 Seats available

In [48]:
df =pd.read_csv(r"C:\Users\DELL\OneDrive\문서\guvi_projects\kadamba_bus_details.csv")
df =pd.read_csv(r"C:\Users\DELL\OneDrive\문서\guvi_projects\kerala_bus_details.csv")
df =pd.read_csv(r"C:\Users\DELL\OneDrive\문서\guvi_projects\rajasthan_bus_details.csv")
df =pd.read_csv(r"C:\Users\DELL\OneDrive\문서\guvi_projects\Telangana_bus_details.csv")
df =pd.read_csv(r"C:\Users\DELL\OneDrive\문서\guvi_projects\up_bus_details.csv")
df =pd.read_csv(r"C:\Users\DELL\OneDrive\문서\guvi_projects\west bengal_bus_details.csv")
df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Esplanade - 176|04:00,Non AC Seater (2+3),04:00,05h 50m,09:50,4.3,INR 165,49 Seats available
1,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) BARASAT-DIGHA via Bally - 38|05:40,Non AC Seater (2+3),05:40,04h 30m,10:10,3.5,INR 161,43 Seats available
2,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,"WBTC (CTC) BARASAT-DIGHA via Esplanade, Karuna...",Non AC Seater (2+3),09:55,05h 00m,14:55,3.5,INR 165,43 Seats available
3,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Bally - 26|10:00,Non AC Seater (2+3),10:00,04h 45m,14:45,3.3,INR 161,40 Seats available
4,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Bally - 26|10:40,Non AC Seater (2+3),10:40,04h 45m,15:25,3.1,INR 161,44 Seats available
...,...,...,...,...,...,...,...,...,...,...
420,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Droupadi City Service,A/C Seater (2+3),15:20,02h 50m,18:10,3.0,180,60 Seats available
421,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Swapna Paribahan,Non AC Seater (2+3),16:55,04h 30m,21:25,3.0,INR 150,25 Seats available
422,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Droupadi Paribahan,A/C Seater (2+3),14:10,02h 48m,16:58,2.7,INR 160,61 Seats available
423,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,KRISHNAKALI,A/C Seater (2+3),14:45,02h 45m,17:30,2.2,INR 165,61 Seats available
424,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...,Droupadi Bus Service,Non AC Seater (2+3),16:20,02h 50m,19:10,2.2,INR 121,54 Seats available

In [50]:
df = df.dropna() #drop null values
a = ",".join(f"{i} {j}"
for i,j in zip(df.columns,df.dtypes)).replace("float64","float").replace("object","text").replace("int64","int") #replace dtypes from pandas to mysql
table_name = "Redbus"
myconnection.cursor().execute(f"create table {table_name} ({a})")
for i in range(len(df)):
    myconnection.cursor().execute(f"insert into {table_name} values {tuple(df.iloc[i])}")
    myconnection.commit()